name: demo
channels:
  - conda-forge
  - defaults
dependencies:
  - matplotlib=3.1
  - numpy=1.18
  - pip
  - python=3.7
  - pip:
    - tensorflow==2.3.0 # or tensorflow-gpu if gpu
    - streamlit==0.64.0
